### ISSUE TITLE
Bad memory restoring speed.

### ISSUE THREAD

**Issue by wjqsec** [h0mbre/Fuzzing#2]
I have the same idea of fuzzing snapshot just like your proejct. However, I found it very slow to use /proc/pid/mem to read and write data between debuger and debugee. In addition, restoring all writable memory pages requires a huge data transfer which is unaffordable to the bus when multiple cores are used in parallel. According to your testing result, ten thousand per seconds seems impossible or it is just because of your small testing binary?

**Comment by h0mbre** [comment]
In my project I didn't use /proc/pid/mem for writing any data. I used /proc/pid/maps for reading only and then used the API `process_vm_writev` to restore snapshots. It is much faster than interacting with /proc.

**Comment by ghost** [comment]
@XinDistance check out https://github.com/marcinguy/fuzzer for @h0mbre fuzzer improvements
